/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import koneksi.koneksi;


/**
 *
 * @author Lenovo
 */
public class data_pelanggan extends javax.swing.JFrame {
private Connection koneksi = new koneksi().connect();
private DefaultTableModel tabmode;



    /**
     * Creates new form data_pelanggan
     */
    public data_pelanggan() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }
     protected void aktif(){
        txt_id.requestFocus();
    }
    protected void kosong(){
        txt_id.setText("");
        txt_nama.setText("");
        txt_tlp.setText("");
        txt_alamat.setText("");
        txt_cari.setText("");
        buttonGroup1.clearSelection();
    }
    
      protected void datatable(){
        Object[] Baris={"ID Pelanggan","Nama Pelanggan","Jenis Kelamin","No Telepon","Alamat"};//nama kolom tabel di form
        tabmode = new DefaultTableModel(null,Baris);
        String cariitem=txt_cari.getText();
        try{
            String sql="SELECT*FROM pelanggan where id_pelanggan like'%"+cariitem+"%' or nama_pelanggan like '%"+cariitem+"%'order by id_pelanggan asc";
            Statement stat= koneksi.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
            });
            }
            tbl_pelanggan.setModel(tabmode);
        }catch (Exception e){
                JOptionPane.showMessageDialog(null,"data gagal dipanggil"+ e);
        } 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_jenis = new javax.swing.JLabel();
        lbl_tlp = new javax.swing.JLabel();
        lbl_alamat = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_tlp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        rLaki = new javax.swing.JRadioButton();
        rPerempuan = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        rCari = new javax.swing.JButton();
        rSimpan = new javax.swing.JButton();
        rUbah = new javax.swing.JButton();
        rHapus = new javax.swing.JButton();
        rBatal = new javax.swing.JButton();
        rKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pelanggan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("DATA PELANGGAN");

        lbl_id.setText("ID Pelanggan");

        lbl_nama.setText("Nama Pelanggan");

        lbl_jenis.setText("Jenis Kelamin");

        lbl_tlp.setText("No Telepon");

        lbl_alamat.setText("Alamat");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_namaKeyTyped(evt);
            }
        });

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        buttonGroup1.add(rLaki);
        rLaki.setText("Laki_laki");

        buttonGroup1.add(rPerempuan);
        rPerempuan.setText("Perempuan");

        jLabel2.setText("ID Pelanggan");

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });

        rCari.setText("cari");
        rCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCariActionPerformed(evt);
            }
        });

        rSimpan.setText("Simpan");
        rSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSimpanActionPerformed(evt);
            }
        });

        rUbah.setText("Ubah");
        rUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUbahActionPerformed(evt);
            }
        });

        rHapus.setText("Hapus");
        rHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rHapusActionPerformed(evt);
            }
        });

        rBatal.setText("Batal");
        rBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBatalActionPerformed(evt);
            }
        });

        rKeluar.setText("Keluar");
        rKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rKeluarActionPerformed(evt);
            }
        });

        tbl_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "Jenis Kelamin", "No Telepon", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(tbl_pelanggan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_jenis)
                                    .addComponent(lbl_nama)
                                    .addComponent(lbl_id))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nama)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rLaki)
                                                .addGap(21, 21, 21)
                                                .addComponent(rPerempuan)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_tlp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 30, Short.MAX_VALUE)))
                        .addGap(121, 121, 121)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(rCari))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(rSimpan)
                .addGap(18, 18, 18)
                .addComponent(rUbah)
                .addGap(18, 18, 18)
                .addComponent(rHapus)
                .addGap(31, 31, 31)
                .addComponent(rBatal)
                .addGap(33, 33, 33)
                .addComponent(rKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rCari))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nama)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_jenis)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rLaki)
                                .addComponent(rPerempuan)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lbl_tlp))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_alamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rKeluar)
                    .addComponent(rBatal)
                    .addComponent(rHapus)
                    .addComponent(rUbah)
                    .addComponent(rSimpan))
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void rSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSimpanActionPerformed
        String jenis= null;
        if(rLaki.isSelected()){
            jenis = "Laki-laki";
        }else if(rPerempuan.isSelected()){
            jenis = "Perempuan";
        }
        String sql="insert into pelanggan values(?,?,?,?,?)";
        try{
            PreparedStatement stat=koneksi.prepareStatement(sql);
            stat.setString(1, txt_id.getText());
            stat.setString(2, txt_nama.getText());
            stat.setString(3, jenis);
            stat.setString(4, txt_tlp.getText());
            stat.setString(5, txt_alamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"data berhasil disimpan");
            kosong();
            txt_id.requestFocus();
        }
         catch (SQLException e){
             JOptionPane.showMessageDialog(null,"data gagal disimpan "+e);
    }
        datatable();
// TODO add your handling code here:
    }//GEN-LAST:event_rSimpanActionPerformed

    private void rUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUbahActionPerformed
        String jenis=null;
        if(rLaki.isSelected()){
            jenis="Laki-laki";
        }else if(rPerempuan.isSelected()){
            jenis="Perempuan";
        }
        try{
        String sql="update pelanggan set nmplgn=?,jenis=?,telepon=?,alamat=?where id='"+txt_id.getText()+"'";
       
            PreparedStatement stat=koneksi.prepareStatement(sql);
            stat.setString(1, txt_nama.getText());
            stat.setString(2, jenis);
            stat.setString(3, txt_tlp.getText());
            stat.setString(4, txt_alamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"data berhasil diubah");
            kosong();
            txt_id.requestFocus();
        }
         catch (SQLException e){
             JOptionPane.showMessageDialog(null,"data gagal diubah "+e);
    }
        datatable();    // TODO add your handling code here:
    }//GEN-LAST:event_rUbahActionPerformed

    private void rHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rHapusActionPerformed
       int ok=JOptionPane.showConfirmDialog(null,"hapus","konfirmasi dialog",JOptionPane.YES_NO_OPTION);
         if(ok==0){
             String sql="delete from pelanggan where id_pelanggan='"+txt_id.getText()+"'";
             try{
                 PreparedStatement stat =koneksi.prepareStatement(sql);
                 stat.executeUpdate();
                 JOptionPane.showMessageDialog(null,"data berhasil dihapus");
                 kosong();
                 txt_id.requestFocus();
            } 
             catch (SQLException e){
                 JOptionPane.showMessageDialog(null,"data gagal dihapus"+e);           
             }
             datatable();
         }
 // TODO add your handling code here:
    }//GEN-LAST:event_rHapusActionPerformed

    private void rBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBatalActionPerformed
        kosong();
        datatable();
// TODO add your handling code here:
    }//GEN-LAST:event_rBatalActionPerformed

    private void rKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rKeluarActionPerformed
       dispose();
 // TODO add your handling code here:
    }//GEN-LAST:event_rKeluarActionPerformed

    private void rCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCariActionPerformed
        datatable();
// TODO add your handling code here:
    }//GEN-LAST:event_rCariActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
      datatable();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txt_cariKeyTyped

    private void txt_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyTyped
    if(txt_nama.getText().length()>25){ 
       JOptionPane.showMessageDialog(null,"Maaf karakter terlalu panjang!");
       evt.consume();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaKeyTyped

    
    private void tbl_pelangganMouseClicked(java.awt.event.MouseEvent evt) {                                             
        int bar = tbl_pelanggan.getSelectedRow();
        String a = tabmode.getValueAt(bar,0).toString(); //table form mulai dari nol klo database dari 1
        String b = tabmode.getValueAt(bar,1).toString();
        String c = tabmode.getValueAt(bar,2).toString();
        String d = tabmode.getValueAt(bar,3).toString();
        String e = tabmode.getValueAt(bar,4).toString();
        
        txt_id.setText(a);
        txt_nama.setText(b);
        if("Laki-laki".equals(c)){
            rLaki.setSelected(true);
            } else{
            rPerempuan.setSelected(true);
            }
        txt_tlp.setText(d);
        txt_alamat.setText(e);
        
    }               
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_jenis;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_tlp;
    private javax.swing.JButton rBatal;
    private javax.swing.JButton rCari;
    private javax.swing.JButton rHapus;
    private javax.swing.JButton rKeluar;
    private javax.swing.JRadioButton rLaki;
    private javax.swing.JRadioButton rPerempuan;
    private javax.swing.JButton rSimpan;
    private javax.swing.JButton rUbah;
    private javax.swing.JTable tbl_pelanggan;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tlp;
    // End of variables declaration//GEN-END:variables
}
