/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import koneksi.koneksi;



/**
 *
 * @author Lenovo
 */
public class kasir extends javax.swing.JFrame {
private Connection koneksi = new koneksi().connect();
private DefaultTableModel tabmode;



    /**
     * Creates new form kasir
     */
    public kasir() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }
     protected void aktif(){
        txt_idkasir.requestFocus();
        cb_agama.setSelectedItem(null);
    }
    protected void kosong(){
        txt_idkasir.setText("");
        txt_nama.setText("");
        txt_tlp.setText("");
        txt_password.setText("");
        txt_alamat.setText("");
        txt_cari.setText("");
        buttonGroup1.clearSelection();
        cb_agama.setSelectedItem(null);
    }
    
      protected void datatable(){
      Object[] Baris={"ID Kasir","Nama Kasir","Jenis Kelamin","No Telepon","Agama","Alamat","Password"};//nama kolom tabel di form
        tabmode = new DefaultTableModel(null,Baris);
        String cariitem=txt_cari.getText();
        try{
            String sql="SELECT*FROM kasir where id_kasir like'%"+cariitem+"%' or nama_kasir like '%"+cariitem+"%'order by id_kasir asc";
            Statement stat= koneksi.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(7),
            });
            }
            tbl_kasir.setModel(tabmode);
   }catch (Exception e){
        JOptionPane.showMessageDialog(null,"data gagal dipanggil"+ e);
        } 
    }


 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_jenis = new javax.swing.JLabel();
        lbl_tlp = new javax.swing.JLabel();
        lbl_agama = new javax.swing.JLabel();
        lbl_alamat = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_idkasir = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        rLaki = new javax.swing.JRadioButton();
        rPerempuan = new javax.swing.JRadioButton();
        txt_tlp = new javax.swing.JTextField();
        cb_agama = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        txt_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        rcari = new javax.swing.JButton();
        rSimpan = new javax.swing.JButton();
        rUbah = new javax.swing.JButton();
        rHapus = new javax.swing.JButton();
        rBatal = new javax.swing.JButton();
        rKeluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_kasir = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("DATA KASIR");

        lbl_id.setText("ID Kasir");

        lbl_nama.setText("Nama Kasir");

        lbl_jenis.setText("Jenis Kelamin");

        lbl_tlp.setText("No Telepon");

        lbl_agama.setText("Agama");

        lbl_alamat.setText("Alamat");

        lbl_password.setText("Password");

        txt_idkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idkasirActionPerformed(evt);
            }
        });

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_namaKeyTyped(evt);
            }
        });

        buttonGroup1.add(rLaki);
        rLaki.setText("Laki-laki");
        rLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rPerempuan);
        rPerempuan.setText("Perempuan");

        cb_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Protestan", "Buddha", "Hindu", " " }));
        cb_agama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_agamaActionPerformed(evt);
            }
        });

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Data Kasir");

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });

        rcari.setText("cari");
        rcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcariActionPerformed(evt);
            }
        });

        rSimpan.setText("Simpan");
        rSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSimpanActionPerformed(evt);
            }
        });

        rUbah.setText("Ubah");
        rUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUbahActionPerformed(evt);
            }
        });

        rHapus.setText("Hapus");
        rHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rHapusActionPerformed(evt);
            }
        });

        rBatal.setText("Batal");
        rBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBatalActionPerformed(evt);
            }
        });

        rKeluar.setText("Keluar");
        rKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rKeluarActionPerformed(evt);
            }
        });

        tbl_kasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_kasir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_agama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_tlp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_jenis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rSimpan)
                                .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rPerempuan))
                            .addComponent(txt_tlp)
                            .addComponent(txt_nama)
                            .addComponent(txt_idkasir)
                            .addComponent(cb_agama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(txt_password)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(rUbah)
                        .addGap(38, 38, 38)
                        .addComponent(rHapus)
                        .addGap(26, 26, 26)
                        .addComponent(rBatal)
                        .addGap(18, 18, 18)
                        .addComponent(rKeluar)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rcari)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_idkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nama)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcari))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_jenis)
                            .addComponent(rLaki)
                            .addComponent(rPerempuan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tlp)
                            .addComponent(txt_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_agama)
                            .addComponent(cb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbl_alamat))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lbl_password))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSimpan)
                    .addComponent(rUbah)
                    .addComponent(rHapus)
                    .addComponent(rBatal)
                    .addComponent(rKeluar))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void rHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rHapusActionPerformed
    int ok=JOptionPane.showConfirmDialog(null,"hapus","konfirmasi dialog",JOptionPane.YES_NO_OPTION);
         if(ok==0){
             String sql="delete from kasir where id_kasir='"+txt_idkasir.getText()+"'";
             try{
                 PreparedStatement stat =koneksi.prepareStatement(sql);
                 stat.executeUpdate();
                 JOptionPane.showMessageDialog(null,"data berhasil dihapus");
                 kosong();
                 txt_idkasir.requestFocus();
            } 
             catch (SQLException e){
                 JOptionPane.showMessageDialog(null,"data gagal dihapus"+e);           
             }
             datatable();
         }    // TODO add your handling code here:
    }//GEN-LAST:event_rHapusActionPerformed

    private void rSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSimpanActionPerformed
    String jenis=null;
        if(rLaki.isSelected()){
            jenis="Laki-laki";
        }else if(rPerempuan.isSelected()){
            jenis="Perempuan";
        }
        String sql="insert into kasir values(?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat=koneksi.prepareStatement(sql);
            stat.setString(1, txt_idkasir.getText());
            stat.setString(2, txt_nama.getText());
            stat.setString(3, jenis);
            stat.setString(4, txt_tlp.getText());
            stat.setString(5, cb_agama.getSelectedItem().toString());
            stat.setString(6, txt_alamat.getText());
            stat.setString(7, txt_password.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"data berhasil disimpan");
            kosong();
            txt_idkasir.requestFocus();
        }
         catch (SQLException e){
             JOptionPane.showMessageDialog(null,"data gagal disimpan "+e);
    }
        datatable(); // TODO add your handling code here:
    }//GEN-LAST:event_rSimpanActionPerformed

    private void rUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUbahActionPerformed
    String jenis=null;
        if(rLaki.isSelected()){
            jenis="Laki-laki";
        }else if(rPerempuan.isSelected()){
            jenis="Perempuan";
        }
        try{
        String sql="update kasir set nama_kasir=?,no_telepon=?,jenis_kelamin=?,agama=?,alamat=?,password=? where id_kasir='"+txt_idkasir.getText()+"'";
       
            PreparedStatement stat=koneksi.prepareStatement(sql);
            stat.setString(1, txt_nama.getText());
            stat.setString(2, jenis);
            stat.setString(3, txt_tlp.getText());
            stat.setString(4, cb_agama.getSelectedItem().toString());
            stat.setString(5, txt_alamat.getText());
            stat.setString(6, txt_password.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"data berhasil diubah");
            kosong();
            txt_idkasir.requestFocus();
        }
         catch (SQLException e){
             JOptionPane.showMessageDialog(null,"data gagal diubah "+e);
    }
        datatable();            // TODO add your handling code here:
    }//GEN-LAST:event_rUbahActionPerformed

    private void rBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBatalActionPerformed
     kosong();
     datatable();// TODO add your handling code here:
    }//GEN-LAST:event_rBatalActionPerformed

    private void rKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rKeluarActionPerformed
    dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_rKeluarActionPerformed

    private void rcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcariActionPerformed
     datatable();    // TODO add your handling code here:
    }//GEN-LAST:event_rcariActionPerformed

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    datatable();
    }    // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariKeyPressed

    private void cb_agamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_agamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_agamaActionPerformed

    private void txt_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyTyped
    if(txt_nama.getText().length()>25){ 
       JOptionPane.showMessageDialog(null,"Maaf karakter terlalu panjang!");
       evt.consume();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaKeyTyped

    private void rLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLakiActionPerformed

    private void txt_idkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idkasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idkasirActionPerformed
    
    private void tbl_kasirMouseClicked(java.awt.event.MouseEvent evt) {
     int bar = tbl_kasir.getSelectedRow();
        String a =tabmode.getValueAt(bar,0).toString(); //table form mulai dari nol klo database dari 1
        String b =tabmode.getValueAt(bar,1).toString();
        String c =tabmode.getValueAt(bar,2).toString();
        String d =tabmode.getValueAt(bar,3).toString();
        String e =tabmode.getValueAt(bar,4).toString();
        String f =tabmode.getValueAt(bar,5).toString();
        String g =tabmode.getValueAt(bar,6).toString();
        
        txt_idkasir.setText(a);
        txt_nama.setText(b);
        if("Laki-laki".equals(c)){
            rLaki.setSelected(true);
        } else{
            rPerempuan.setSelected(true);
        }
        txt_tlp.setText(d);
        cb_agama.setSelectedItem(e);
        txt_alamat.setText(f);
        txt_password.setText(g);
                       // TODO add your handling code here:
    }
    
       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_agama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_agama;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_jenis;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_tlp;
    private javax.swing.JButton rBatal;
    private javax.swing.JButton rHapus;
    private javax.swing.JButton rKeluar;
    private javax.swing.JRadioButton rLaki;
    private javax.swing.JRadioButton rPerempuan;
    private javax.swing.JButton rSimpan;
    private javax.swing.JButton rUbah;
    private javax.swing.JButton rcari;
    private javax.swing.JTable tbl_kasir;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_idkasir;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_tlp;
    // End of variables declaration//GEN-END:variables
}
